# Generated by Django 2.0.5 on 2018-06-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMessage',
            fields=[
                ('id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='key')),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='title')),
                ('img_url', models.CharField(max_length=500, verbose_name='image')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('message', models.CharField(max_length=500, verbose_name='message')),
            ],
            options={
                'verbose_name': '用户留言信息',
                'verbose_name_plural': '用户留言信息',
            },
        ),
    ]
